name: Deploy React Nattapong
on: 
  push:
    branches:
      - master
      # - features/**
      # - "!features/authen"
  workflow_dispatch:
  pull_request:
    types:
      - opened
jobs:
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v5
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install depen
        run: bun i
      - name: Build
        run: bun run build
      - name: Upload dist
        run: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: dist/
  deploy:
    needs: 
        - lint
    runs-on: ubuntu-latest
    steps:
      - name: Download-dist
        uses: actions/download-artifact@v4
        with:
          - name: dist-folder
            path: dist/
      - name: Deploy
        run: echo "deployyyyyyyy"