name: Deploy React CSR
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v5
        with:
          bun-version: 1.2.18
      - name: Install and Cache
        uses: ./.github/actions/install-cache
      - name: Build
        run: bun run build
      - name: List dist/
        run: ls dist
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Clone repo
        uses: actions/checkout@v5
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist-folder
          path: dist
      - name: Deploy
        uses: ./.github/actions/deploy-surge
        with:
          token: ${{ secrets.SURGE_TOKEN }}
          email: ${{ vars.SURGE_EMAIL }}
          dist-folder: dist
          domain: work-shop1.surge.sh