name: Deploy React Nattapong
on: 
  push:
    branches:
      - master
      # - features/**
      # - "!features/authen"
  workflow_dispatch:
  pull_request:
    types:
      - opened
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v5
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Caching
      - uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
      - name: Install depen
        run: bun i
      - name: Build
        run: bun run build
      - name: List dist/
        run: ls dist
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: dist/
  deploy:
    needs: 
        - build
    runs-on: ubuntu-latest
    steps:
      - name: Download-dist
        uses: actions/download-artifact@v4
        with:
            name: dist-folder
            path: dist
      - name: Deploy
        run: echo "deployyyyyyyy"