name: Deploy React Nattapong
on: 
  push:
    branches:
      - master
      # - features/**
      # - "!features/authen"
  workflow_dispatch:
  pull_request:
    types:
      - opened
# env:
#   BUN_VERSION: 1.2.18
jobs:
  build:
    environment: natpong
    runs-on: ubuntu-latest
    steps:
      - name: Print Bun version
        run: echo "Bun version:${{ vars.BUN_VERSION }}"
      - name: Print Api KEY
        run: echo "API_KEY:${{ secrets.API_KEY }}"
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ vars.BUN_VERSION }}
      - name: Caching
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
      - name: Install depen
        run: bun i
      - name: Build
        run: bun run build
      - name: List dist/
        run: ls dist
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: dist/
  deploy:
    if: ${{github.ref == 'refs/heads/master'}}
    needs: 
        - build
    runs-on: ubuntu-latest
    steps:
      - name: Download-dist
        uses: actions/download-artifact@v4
        with:
            name: dist-folder
            path: dist
      - name: Deploy
        run: echo "deployyyyyyyy"