name: Matrix
on:
    push:
jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                bun_version: ["1.2.0","1.2.1","1.2.16"]
                browser: ["firefox","chrome","safari"]
        steps:
            - name: Print bun veriosn and test browser
              run: echo "${{matrix.bun_version}} - ${{matrix.browser}}"